# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - psscripts
    exclude:
    - README.md
pr:
  branches:
    include:
    - main
  paths:
    include:
    - psscripts
    exclude:
    - README.md

pool:
  vmImage: ubuntu-latest

jobs:
- job: CreateRG
  displayName: CreateRG
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'azure-spn'
      scriptType: 'ps'
      scriptLocation: 'scriptPath'
      scriptPath: 'psscripts/createrg.ps1'
